server:
  port: 8080

spring:
  profiles:
    active: local

  application:
    name: sellerpcs_batch

  mvc:
    throw-exception-if-no-handler-found: true

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.skplanet.sellerpcs.batch.domain


#"0 0 * * * *" = the top of every hour of every day.
#"*/10 * * * * *" = every ten seconds.
#"0 0 8-10 * * *" = 8, 9 and 10 o'clock of every day.
#"0 0 6,19 * * *" = 6:00 AM and 7:00 PM every day.
#"0 0/30 8-10 * * *" = 8:00, 8:30, 9:00, 9:30, 10:00 and 10:30 every day.
#"0 0 9-17 * * MON-FRI" = on the hour nine-to-five weekdays
#"0 0 0 25 12 ?" = every Christmas Day at midnight
emailalarm:
  schedule: "*/10 * * * * *"

logging:
  config:
    classpath: logback-spring.xml

---
spring:
  profiles: local
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url:
    username:
    password:
    max-active: 20
    max-idle: 20
    max-wait: 15000
    initial-size: 5
    validation-query: select 1 from dual
    test-on-borrow: true
    test-while-idle: false

---

spring:
  profiles: prd
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url:
    username:
    password:
    max-active: 20
    max-idle: 20
    max-wait: 15000
    initial-size: 5
    validation-query: select 1 from dual
    test-on-borrow: true
    test-while-idle: false